Oled display
chirimen-oh/echigo-examples pull request #15
Opened 2016-11-05 11:59 UTC by tadfmac

[Grove I2C OLED Display](https://www.seeedstudio.com/grove-oled-display-12864-p-781.html) example

2016-11-07 09:03 UTC, MSakamaki requested changes

2016-11-07 09:03 UTC, MSakamaki commented on i2c-grove-oledDisplay/js/oledDisplay.js
> +    var self = this;
`this`を`self`に退避していますが、ここは[アロー関数](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/arrow_functions)を利用したほうが良いと思います。
他の`var self = this;`も同様にアロー関数で対応したほうが、~~あと`windows.self`の存在も忘れないでおいてあげてください・・・~~

ex.

``` javascript
drawString: function(row,col,string){

  return new Promise((resolve, reject) => {
    this.i2cPort.open(OLED_CONST.Address).then(i2cSlave => {
      this.i2cSlave = i2cSlave;
      console.log("start drawString");
      this.drawStringQ(row, col);
      this.playSequence().then(resolve);
    });
  });
}
```

2016-11-07 09:03 UTC, MSakamaki commented on i2c-grove-oledDisplay/js/oledDisplay.js
> +            if(self.funcQueue[self.index].mode == OLED_CONST.Command_Mode){
等価評価は`==`ではなく`===`を使ったほうが良いかも。
(`==`だと`0x00 == '0x00'`が`true`評価とかになてしまったり)

2016-11-07 09:16 UTC, MSakamaki requested changes
Mozilla コーディングスタイルガイドガイド分追加

2016-11-07 09:16 UTC, MSakamaki commented on i2c-grove-oledDisplay/js/oledDisplay.js
> +  BasicFont : [
細かいですけれど、javascript objectはcamelCaseで

誤：`BasicFont `
正：`basicFont `

https://developer.mozilla.org/ja/docs/Mozilla/Developer_Guide/Mozilla_Coding_Style_Guide#JavaScript_objects

2016-11-07 11:54 UTC, tadfmac commented
@MSakamaki さん レビュー有難うございます！
全て対応予定です！

2016-11-14 09:31 UTC, tadfmac commented
@MSakamaki さん
遅くなりましたが、頂いたご指摘に対応いたしました。

2016-11-15 02:53 UTC, MSakamaki approved these changes
[![LGTM](https://lgtm.in/p/cYtYqlh3q)](https://lgtm.in/i/cYtYqlh3q)

[:+1:](https://lgtm.in/u/cYtYqlh3q)

2016-11-16 10:34 UTC, dadaa commented on i2c-grove-oledDisplay/js/main.js
> +  var head = document.querySelector('#head');
https://dxr.mozilla.org/mozilla-central/source/devtools/.eslintrc.js
では、var もゆるしてますけれども、let と const に統一した方が良いかと思いました。
というわけで CHIRIMEN 向けでは https://dxr.mozilla.org/mozilla-central/source/devtools/.eslintrc.js も修正したいと思います。
というわけで、今回はこのままで行っちゃいましょう

2016-11-16 10:38 UTC, dadaa commented on i2c-grove-oledDisplay/js/oledDisplay.js
> +    var obj = {};
var obj = { mode: mode, param: param };
で良いかとー

2016-11-16 10:39 UTC, dadaa commented on i2c-grove-oledDisplay/js/oledDisplay.js
> +          for(var cnt=0;cnt < OLED_CONST.packetSize;cnt ++){
変数の名前とか、僕はあまり省略しないんですけど、どうしましょ？

2016-11-18 07:06 UTC, MSakamaki commented on i2c-grove-oledDisplay/js/oledDisplay.js
> +    var obj = {};
もっというとこうだったりします？

```javascript
this.funcQueue.push({
  mode: mode,
  param: param
});
```

2016-11-18 07:27 UTC, MSakamaki commented on i2c-grove-oledDisplay/js/oledDisplay.js
> +          for(var cnt=0;cnt < OLED_CONST.packetSize;cnt ++){
スコープが狭い変数であれば、ある程度省略しても大丈夫じゃないでしょうか派なので、私は問題ないかなと思っています。

個人的に変数名とかの話であれば、`this.index`や`this.seq`などが何のindexかseqなのか変数から読み取りづらい(`OledDisplay.index`, `OledDisplay.seq`のように)ので、そちらの名前のほうが気にはなっていました(候補としては`OledDisplay.register.index`や`OledDisplay.registerIndex`等・・・？)

とはいえ修正するほどとは思っていない程度の気になり方です。

2016-11-18 13:34 UTC, tadfmac commented on i2c-grove-oledDisplay/js/oledDisplay.js
> +    var obj = {};
みなさま、ありがとうございます。
こちらは、どちらかの案に修正させて頂きたいと思います。
私は @dadaa さんから頂いた方が判りやすいかな？とおもったのですが、
如何でしょうか。

2016-11-18 13:45 UTC, tadfmac commented on i2c-grove-oledDisplay/js/oledDisplay.js
> +          for(var cnt=0;cnt < OLED_CONST.packetSize;cnt ++){
ありがとうございます。
私も @MSakamakiさんと同じ感覚です。

既存のexamplesのコードを拝見しても、valueをvと省略したり、カウンターにi を使ったりを許容しているように見えますので、少々ご指摘の基準が不明瞭に思えます。

2016-11-18 15:02 UTC, tadfmac commented on i2c-grove-oledDisplay/js/oledDisplay.js
> +          for(var cnt=0;cnt < OLED_CONST.packetSize;cnt ++){
this.seqはthis.sequenceに修正させていただこうと思いました。お2人のご指摘で気づきを得られました。ありがとうございます。
他にも省略箇所はあり、cntやvなどですが、これらは今のところ前例同様で慣例的な変数名でもあるので特に修正の必要性は感じていません。

2016-11-21 03:05 UTC, MSakamaki commented on i2c-grove-oledDisplay/js/oledDisplay.js
> +    var obj = {};
@tadfmac 
私は @dadaa さんの案でも自分の内容でもどちららでも大丈夫だと思ってますｖ
(この程度ならば好みの問題かなってレベルなので)

指摘で`obj`に格納しなかった理由は、他で`obj`変数を参照していないのでスコープを汚さないために直接渡しのほうが良いかなと思って上のように書きました。

2017-01-16 04:33 UTC, merged